#pragma once

#define __imp__XamInputGetState doritos_XamInputGetState
#define __imp__XamInputGetKeystroke doritos_XamInputGetKeystroke
#define __imp__XamInputGetKeystrokeEx doritos_XamInputGetKeystrokeEx
#define __imp__XamContentCreateEx doritos_XamContentCreateEx
#define __imp__XamContentClose doritos_XamContentClose
#define __imp__XamContentGetLicenseMask doritos_XamContentGetLicenseMask
#define __imp__XamContentCreateEnumerator doritos_XamContentCreateEnumerator
#define __imp__XamContentGetDeviceData doritos_XamContentGetDeviceData
#define __imp__XamUserGetName doritos_XamUserGetName
#define __imp__XamUserGetXUID doritos_XamUserGetXUID
#define __imp__XamUserGetDeviceContext doritos_XamUserGetDeviceContext
#define __imp__XamUserGetSigninState doritos_XamUserGetSigninState
#define __imp__XamUserGetSigninInfo doritos_XamUserGetSigninInfo
#define __imp__XamUserCheckPrivilege doritos_XamUserCheckPrivilege
#define __imp__XamShowSigninUI doritos_XamShowSigninUI
#define __imp__XamUserReadProfileSettings doritos_XamUserReadProfileSettings
#define __imp__XamUserWriteProfileSettings doritos_XamUserWriteProfileSettings
